server:
  port: 9001

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.214.212:8848 #配置nacos地址
  main:
    allow-bean-definition-overriding: true  #允许指向同一个实例

ribbon:
  ReadTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000 #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
